# Generated by Django 4.0 on 2021-12-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phone_image_phone_release_date_phone_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='lte_exists',
            field=models.BooleanField(null=True),
        ),
    ]
